---

- name: Config wordpress
  block:
    - name: Put correct wp-config.php
      template:
        src: templates/wp-config.php.j2
        dest: "{{root_dir}}/wordpress/wp-config.php"

    - name: Configurate rights for nginx ueser
      file:
        dest: "{{root_dir}}/wordpress"
        owner: nginx
        group: nginx
        mode: 0755
        recurse: yes

    - name: Put wordpress.conf
      template:
        src: templates/wordpress.conf.j2
        dest: "/etc/nginx/conf.d/wordpress.conf"

